// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi5c7Pws7GqhBxu7FVNzJKv_YJcKcbghc',
    appId: '1:718505391457:web:daa2bb3279d1fedc4d4120',
    messagingSenderId: '718505391457',
    projectId: 'flutterguide-6cfc5',
    authDomain: 'flutterguide-6cfc5.firebaseapp.com',
    storageBucket: 'flutterguide-6cfc5.firebasestorage.app',
    measurementId: 'G-Q4J7H91P2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_pCfcAQa6rGXXd_DThEF2MpFHJdXAkok',
    appId: '1:718505391457:android:6a0fb5b6e3bbada94d4120',
    messagingSenderId: '718505391457',
    projectId: 'flutterguide-6cfc5',
    storageBucket: 'flutterguide-6cfc5.firebasestorage.app',
  );
}
